[blue]
# Replace with actual blue EC2 IP
blue_instance ansible_host=10.0.1.10 ansible_user=ubuntu

[green]
# Replace with actual green EC2 IP
green_instance ansible_host=10.0.2.10 ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
